package cmd

import (
	"context"
	"fmt"
	"os"
	"os/signal"
	"sort"
	"strings"
	"syscall"
	"time"

	"github.com/spf13/cobra"

	"github.com/dynatrace-oss/dtctl/pkg/config"
	"github.com/dynatrace-oss/dtctl/pkg/exec"
	"github.com/dynatrace-oss/dtctl/pkg/output"
	"github.com/dynatrace-oss/dtctl/pkg/recipes"
	"github.com/dynatrace-oss/dtctl/pkg/resources/segment"
	"github.com/dynatrace-oss/dtctl/pkg/util/template"
)

// recipesCmd is the bootstrap call: environment facts plus the recipe index.
// `dtctl commands` answers "what can I run?"; `dtctl recipes` answers "what
// is true here?" (docs/dev/RECIPES_CONCEPT.md).
var recipesCmd = &cobra.Command{
	Use:   "recipes",
	Short: "Environment briefing: verified facts and the recipe index for the current context",
	Long: `Show the environment briefing for the current context: discovered facts
(capabilities, entity census, data objects, field carriage, scoping rules)
plus a one-line-per-recipe index of verified, parameterized DQL queries.

Recipes are per-environment query knowledge, generated by probing the live
environment (see 'dtctl recipes discover'). Consume a recipe with:

  dtctl describe recipe <name>                    # full DQL, params, stamp
  dtctl query --recipe <name> --set param=value   # execute
  dtctl verify query --recipe <name>              # render + validate only

Examples:
  # The agent-bootstrap call (facts + recipe index)
  dtctl recipes
  dtctl recipes -o json

  # Generate/refresh the recipe book for this context
  dtctl recipes discover --pack ./base-pack.yaml
  dtctl recipes refresh
`,
	RunE: func(cmd *cobra.Command, args []string) error {
		cfg, err := LoadConfig()
		if err != nil {
			return err
		}
		lib, err := recipes.LoadLibrary(config.ConfigDir(), cfg.CurrentContext)
		if err != nil {
			return err
		}
		briefing := recipes.BuildBriefing(lib, nil)

		if outputFormat == "table" && !agentMode {
			printBriefingHuman(briefing)
			return nil
		}
		printer := NewPrinter()
		if ap := enrichAgent(printer, "recipes", "recipes"); ap != nil {
			suggestions := []string{
				"# full recipe (DQL, params, stamp): dtctl describe recipe <name>",
				"# execute: dtctl query --recipe <name> [--set param=value]",
			}
			if lib.Book == nil {
				suggestions = append(suggestions, "# no recipe book yet — generate one: dtctl recipes discover")
			}
			ap.SetSuggestions(suggestions)
			ap.SetWarnings(briefing.Warnings)
		}
		return printer.Print(briefing)
	},
}

// recipesDiscoverCmd generates (or regenerates) the recipe book for the
// current context by probing the live environment: facts battery, capability
// evaluation, guard checks, and per-recipe probe execution with stamps.
var recipesDiscoverCmd = &cobra.Command{
	Use:   "discover",
	Short: "Probe the environment and generate the recipe book for the current context",
	Long: `Run the discovery battery (entity census, data objects, buckets, field
carriage) against the current context, evaluate the installed packs'
capability definitions and guards, probe-execute each recipe, and write the
per-context recipe book to <config-dir>/recipes/<context>.yaml.

Discovery is a real consumption event: probes run cheapest-first, carry scan
caps, and a global budget aborts with a partial book rather than overrunning.
A consumption receipt is printed at the end.

Examples:
  # Install a pack and generate the book
  dtctl recipes discover --pack ./dynatrace-recipes.yaml

  # Facts only (no recipe probing)
  dtctl recipes discover --facts-only
`,
	RunE: runRecipesDiscover,
}

// recipesRefreshCmd re-runs discovery over the installed packs: re-probes
// facts, re-evaluates guards and probe-empty disables, and refreshes stamps.
var recipesRefreshCmd = &cobra.Command{
	Use:   "refresh",
	Short: "Re-run probes, refresh stamps, and re-evaluate disabled recipes",
	Long: `Re-run the discovery battery and recipe probes for the current context,
refreshing the recipe book in place. probe-empty disables are re-probed
(absence of events is weak evidence); local recipes are re-stamped but their
bodies are never rewritten.`,
	RunE: runRecipesDiscover,
}

func runRecipesDiscover(cmd *cobra.Command, args []string) error {
	cfg, c, err := SetupClient()
	if err != nil {
		return err
	}
	if cfg.CurrentContext == "" {
		return fmt.Errorf("no current context — recipes are per-context; use --context or `dtctl ctx use`")
	}
	configDir := config.ConfigDir()

	// Install any packs passed explicitly (the explicit act of trust).
	packFiles, _ := cmd.Flags().GetStringArray("pack")
	for _, pf := range packFiles {
		p, err := recipes.InstallPack(configDir, pf)
		if err != nil {
			return err
		}
		fmt.Fprintf(os.Stderr, "Installed pack %s@%s\n", p.Metadata.Name, p.Metadata.Version)
	}

	prevBook, err := recipes.LoadBook(recipes.BookPath(configDir, cfg.CurrentContext))
	if err != nil {
		return err
	}
	var packs []*recipes.Pack
	if prevBook != nil && len(prevBook.Metadata.Packs) > 0 && len(packFiles) == 0 {
		lib, lerr := recipes.LoadLibrary(configDir, cfg.CurrentContext)
		if lerr != nil {
			return lerr
		}
		packs = lib.Packs
	} else {
		packs, err = recipes.InstalledPacks(configDir)
		if err != nil {
			return err
		}
	}
	if len(packs) == 0 {
		fmt.Fprintln(os.Stderr, "No packs installed — generating a facts-only recipe book. Install a pack with --pack <file>.")
	}

	factsOnly, _ := cmd.Flags().GetBool("facts-only")
	budgetQueries, _ := cmd.Flags().GetInt("budget-queries")
	budgetSeconds, _ := cmd.Flags().GetFloat64("budget-seconds")
	scanLimitGB, _ := cmd.Flags().GetFloat64("scan-limit-gbytes")

	executor := NewDQLExecutorFromConfig(cfg, c)
	runner := &discoverRunner{executor: executor, scanLimitGB: scanLimitGB}

	// Segments come from the API, not DQL — fetched here and passed as facts.
	var segFacts []recipes.SegmentFact
	if segs, serr := segment.NewHandler(c).List(); serr == nil {
		for _, s := range segs.FilterSegments {
			segFacts = append(segFacts, recipes.SegmentFact{UID: s.UID, Name: s.Name, Description: s.Description})
		}
	}

	// Cancel cleanly on Ctrl+C: discovery aborts, no partial book is written.
	ctx, cancel := context.WithCancel(context.Background())
	defer cancel()
	sigCh := make(chan os.Signal, 1)
	signal.Notify(sigCh, os.Interrupt, syscall.SIGTERM)
	defer signal.Stop(sigCh)
	go func() {
		<-sigCh
		cancel()
	}()

	fmt.Fprintf(os.Stderr, "Discovering environment for context %q (%d pack(s))...\n", cfg.CurrentContext, len(packs))
	book, report, err := recipes.Discover(ctx, runner, packs, recipes.DiscoverOptions{
		ContextName:   cfg.CurrentContext,
		Generator:     "dtctl recipes discover v0.1",
		Segments:      segFacts,
		PrevBook:      prevBook,
		FactsOnly:     factsOnly,
		BudgetQueries: budgetQueries,
		BudgetSeconds: budgetSeconds,
	})
	if err != nil {
		return err
	}

	bookPath := recipes.BookPath(configDir, cfg.CurrentContext)
	if err := recipes.WriteBook(bookPath, book); err != nil {
		return err
	}

	receipt := struct {
		Book     string   `json:"book" yaml:"book"`
		Queries  int      `json:"queries" yaml:"queries"`
		Seconds  float64  `json:"seconds" yaml:"seconds"`
		Probed   int      `json:"probed" yaml:"probed"`
		Disabled int      `json:"disabled" yaml:"disabled"`
		Unprobed int      `json:"unprobed" yaml:"unprobed"`
		Notes    []string `json:"notes,omitempty" yaml:"notes,omitempty"`
	}{bookPath, report.Queries, float64(int(report.Seconds*10)) / 10, report.Probed, report.Disabled, report.Unprobed, report.Notes}

	if outputFormat == "table" && !agentMode {
		fmt.Printf("Recipe book written: %s\n", bookPath)
		fmt.Printf("Consumption receipt: %d queries, %.1fs query time\n", receipt.Queries, receipt.Seconds)
		if !factsOnly {
			fmt.Printf("Recipes: %d stamped, %d disabled with evidence, %d unprobed\n", receipt.Probed, receipt.Disabled, receipt.Unprobed)
		}
		for _, n := range receipt.Notes {
			fmt.Printf("  note: %s\n", n)
		}
		return nil
	}
	printer := NewPrinter()
	enrichAgent(printer, "recipes", "discover")
	return printer.Print(receipt)
}

// discoverRunner adapts the DQL executor to the generator's Runner interface.
// Every probe carries the scan cap; queries are tagged for observability.
type discoverRunner struct {
	executor    *exec.DQLExecutor
	scanLimitGB float64
}

func (r *discoverRunner) RunQuery(ctx context.Context, dql string) (*recipes.RunResult, error) {
	start := time.Now()
	resp, err := r.executor.ExecuteQueryWithContext(ctx, dql, exec.DQLExecuteOptions{
		DefaultScanLimitGbytes: r.scanLimitGB,
		ClientContext:          "recipes-discover",
	})
	if err != nil {
		return nil, err
	}
	if resp == nil {
		return nil, context.Canceled
	}
	return &recipes.RunResult{
		Records: resp.GetRecords(),
		Seconds: time.Since(start).Seconds(),
		Partial: exec.PartialNotification(resp),
	}, nil
}

// printBriefingHuman renders the briefing for a terminal.
func printBriefingHuman(b *recipes.Briefing) {
	const w = 14
	output.DescribeKV("Context:", w, "%s", b.Context)
	if b.GeneratedAt != "" {
		age := b.FactsAge
		if age == "" {
			age = "unknown"
		}
		output.DescribeKV("Generated:", w, "%s (age %s)", b.GeneratedAt, age)
	}
	for _, p := range b.Packs {
		output.DescribeKV("Pack:", w, "%s@%s", p.Name, p.Version)
	}
	for _, warning := range b.Warnings {
		output.PrintWarning("%s", warning)
	}
	if f := b.Facts; f != nil {
		if len(f.Capabilities) > 0 {
			output.DescribeKV("Capabilities:", w, "%s", strings.Join(f.Capabilities, ", "))
		}
		if len(f.Absent) > 0 {
			output.DescribeKV("Absent:", w, "%s", strings.Join(f.Absent, ", "))
		}
		if len(f.EntityTypes) > 0 {
			output.DescribeKV("Entities:", w, "%s", topEntityTypes(f.EntityTypes, 12))
		}
		if len(f.Buckets) > 0 {
			output.DescribeKV("Buckets:", w, "%s", strings.Join(f.Buckets, ", "))
		}
		if len(f.FieldCarriage) > 0 {
			output.DescribeSection("Field carriage (fraction of records carrying the field)")
			tables := sortedKeys(f.FieldCarriage)
			for _, t := range tables {
				fields := f.FieldCarriage[t]
				parts := make([]string, 0, len(fields))
				for _, fn := range sortedKeys(fields) {
					parts = append(parts, fmt.Sprintf("%s=%.2f", fn, fields[fn]))
				}
				fmt.Printf("  %s: %s\n", t, strings.Join(parts, "  "))
			}
		}
		if len(b.Scoping) > 0 {
			output.DescribeSection("Scoping (how to reference an entity in a signal)")
			for _, et := range sortedKeys(b.Scoping) {
				for _, sig := range sortedKeys(b.Scoping[et]) {
					rule := b.Scoping[et][sig]
					how := rule.Filter
					if rule.Hop != "" {
						how = "hop via " + rule.Hop + " topology (direct filter is partial)"
					}
					cov := ""
					if rule.Coverage != nil {
						cov = fmt.Sprintf("  [coverage %.2f]", *rule.Coverage)
					}
					fmt.Printf("  %s -> %s: %s%s\n", et, sig, how, cov)
				}
			}
		}
		for _, n := range f.Notes {
			output.DescribeKV("Note:", w, "%s", n)
		}
	}

	output.DescribeSection(fmt.Sprintf("Recipes (%d)", len(b.Recipes)))
	for _, r := range b.Recipes {
		status := "unstamped"
		if r.Stamped {
			if r.Records != nil {
				status = fmt.Sprintf("%d rec @ %s", *r.Records, shortDate(r.At))
			} else {
				status = "stamped"
			}
		}
		if len(r.RequiredParams) > 0 {
			status += " (needs --set " + strings.Join(r.RequiredParams, ",") + ")"
		}
		fmt.Printf("  %-32s %-28s %s\n", r.Name, status, r.Description)
	}
	if len(b.Disabled) > 0 {
		output.DescribeSection(fmt.Sprintf("Disabled with evidence (%d) — negative knowledge, often the most valuable", len(b.Disabled)))
		for _, d := range b.Disabled {
			fmt.Printf("  %-32s [%s] %s\n", d.Name, d.Class, d.Reason)
		}
	}
	fmt.Println()
	fmt.Println("Use: dtctl describe recipe <name> | dtctl query --recipe <name> --set k=v")
}

func topEntityTypes(census map[string]int64, n int) string {
	type kv struct {
		k string
		v int64
	}
	entries := make([]kv, 0, len(census))
	for k, v := range census {
		entries = append(entries, kv{k, v})
	}
	sort.Slice(entries, func(i, j int) bool {
		if entries[i].v != entries[j].v {
			return entries[i].v > entries[j].v
		}
		return entries[i].k < entries[j].k
	})
	var parts []string
	for i, e := range entries {
		if i >= n {
			parts = append(parts, fmt.Sprintf("(+%d more types)", len(entries)-n))
			break
		}
		parts = append(parts, fmt.Sprintf("%s:%d", e.k, e.v))
	}
	return strings.Join(parts, " ")
}

func sortedKeys[M ~map[string]V, V any](m M) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}

func shortDate(at string) string {
	if t, err := time.Parse(time.RFC3339, at); err == nil {
		return t.Format("2006-01-02 15:04")
	}
	return at
}

// recipeExecution carries a resolved recipe into the query command: rendered
// DQL, envelope enrichment, and the stamp-refresh observer.
type recipeExecution struct {
	name        string
	warnings    []string
	suggestions []string
	observe     func(exec.ObservedResult) []string
}

// resolveRecipeForRun resolves and renders a recipe for `query --recipe` /
// `verify query --recipe`.
func resolveRecipeForRun(cfg *config.Config, name string, setFlags []string) (*recipeExecution, string, error) {
	lib, err := recipes.LoadLibrary(config.ConfigDir(), cfg.CurrentContext)
	if err != nil {
		return nil, "", err
	}
	res, err := lib.Lookup(name)
	if err != nil {
		return nil, "", err
	}

	setVals := map[string]string{}
	if len(setFlags) > 0 {
		vars, perr := template.ParseSetFlags(setFlags)
		if perr != nil {
			return nil, "", fmt.Errorf("invalid --set flag: %w", perr)
		}
		for k, v := range vars {
			setVals[k] = fmt.Sprintf("%v", v)
		}
	}
	rendered, err := recipes.Render(res.Recipe, setVals)
	if err != nil {
		return nil, "", fmt.Errorf("recipe %q: %w", name, err)
	}

	re := &recipeExecution{name: name}
	if res.Disabled != nil {
		re.warnings = append(re.warnings, fmt.Sprintf(
			"recipe %q is disabled on this environment (%s: %s) — executing anyway; a non-empty result resurrects it",
			name, res.Disabled.Class, res.Disabled.Reason))
	}
	if !res.InBook && res.Disabled == nil && lib.Book != nil {
		re.warnings = append(re.warnings, fmt.Sprintf("recipe %q comes from a pack and is not stamped for this environment — run `dtctl recipes refresh`", name))
	}
	for _, f := range res.Recipe.Followups {
		if lib.Book != nil {
			if _, dead := lib.Book.Disabled[f]; dead {
				continue // never steer toward a known-dead recipe
			}
		}
		target, terr := lib.Lookup(f)
		if terr != nil {
			continue // unresolved cross-pack edge: dropped
		}
		hint := ""
		if req := recipes.RequiredParams(target.Recipe); len(req) > 0 {
			hint = " --set " + strings.Join(req, "=... --set ") + "=..."
		}
		re.suggestions = append(re.suggestions, fmt.Sprintf("# next: dtctl query --recipe %s%s", f, hint))
	}

	prevStamp := res.Recipe.LastRun
	re.observe = func(obs exec.ObservedResult) []string {
		var extra []string
		if prevStamp != nil && prevStamp.Params == recipes.ParamsProvenanceDefault &&
			rendered.Provenance == recipes.ParamsProvenanceDefault &&
			prevStamp.Records != nil && *prevStamp.Records > 0 && obs.Records == 0 {
			extra = append(extra, fmt.Sprintf(
				"recipe %q: was %d records at %s, 0 now — either nothing matches now, or ingest changed since then (not proof of absence)",
				name, *prevStamp.Records, prevStamp.At))
		}
		if lib.Book == nil {
			return extra
		}
		// A custom-param run never overwrites the default-param baseline —
		// drift reasoning applies only to default-param stamps (§4.0).
		if rendered.Provenance != recipes.ParamsProvenanceDefault &&
			prevStamp != nil && prevStamp.Params == recipes.ParamsProvenanceDefault {
			return extra
		}
		stamp := recipes.NewStamp(obs.Records, obs.Seconds, rendered.Provenance, obs.Partial, rendered.DQL)
		resurrect := res.Disabled != nil && obs.Records > 0
		if err := recipes.UpdateStamp(lib.BookPath, name, res.Source, stamp, resurrect); err != nil {
			extra = append(extra, "recipe stamp not refreshed (read-only?): "+err.Error())
		} else if resurrect {
			extra = append(extra, fmt.Sprintf("recipe %q returned %d records and was resurrected from disabled", name, obs.Records))
		}
		return extra
	}
	return re, rendered.DQL, nil
}

func init() {
	rootCmd.AddCommand(recipesCmd)
	recipesCmd.AddCommand(recipesDiscoverCmd)
	recipesCmd.AddCommand(recipesRefreshCmd)

	for _, c := range []*cobra.Command{recipesDiscoverCmd, recipesRefreshCmd} {
		c.Flags().StringArray("pack", nil, "Recipe pack file to install into the pack store before discovery (repeatable)")
		c.Flags().Bool("facts-only", false, "Discover facts and scoping only; skip recipe probing")
		c.Flags().Int("budget-queries", 0, "Discovery budget: max queries (default 250)")
		c.Flags().Float64("budget-seconds", 0, "Discovery budget: max cumulative query seconds (default 600)")
		c.Flags().Float64("scan-limit-gbytes", 25, "Scan cap applied to every discovery probe")
	}
}
